name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build 06 Reactor
        shell: bash
        run: |
          # Navigate into the 06-reactor directory
          cd 06-reactor

          # Loop through each project directory and build the project
          for project in */ ; do
            # Only consider directories
            if [[ -d "$project" ]]; then
              echo "Building project: $project"
              # Navigate into project directory
              cd $project

              # Install project dependencies using pnpm
              pnpm install

              # Build the project - assumes a script named 'build' is present in package.json
              pnpm run build

              # Create a directory for the project's build artifacts in the 06-reactor
              mkdir -p ../build-artifacts/${project%/}

              # Move build artifacts to the dedicated directory
              mv dist/* ../build-artifacts/${project%/}

              # Navigate back to the 06-reactor directory
              cd ..

              # Remove the project directory, now that the dist has been moved out
              rm -rf ${project}
            fi
          done

          # Now move all the build artifacts back into the 06-reactor directory
          mv build-artifacts/* .
          # Clean up the now empty build-artifacts directory
          rmdir build-artifacts

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
